name: Deploy Bot

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          SAGA_URL: ${{ secrets.SAGA_URL }}
          CHECK_INTERVAL: 60
        run: |
          python saga_bot.py

      - name: Debug env
        run: echo "Token starts with: ${{ secrets.TELEGRAM_TOKEN }}"

      - name: Clear known_offers.txt cache
        run: |
          if [ -f known_offers.txt ]; then rm known_offers.txt; fi
